controllers:
    resource: ../src/Controller/
    type: attribute

app_contact:
    path: /contact
    controller: App\Controller\ContactController::index
    methods: [GET, POST]
    
app_manage_contact:
    path: /manage-contact-message
    controller: App\Controller\ManageContactController::indexAction
    methods: [GET]

app_home:
    path: /
    controller: App\Controller\IndexController::indexAction
    
app_about:
    path: /about
    controller: App\Controller\AboutController::indexAction
    
app_view_contact:
    path: /view-contact-messages
    controller: App\Controller\ViewContactController::indexAction

app_admin_contact:
    path: /admin-contact-reply
    controller: App\Controller\AdminReplyContactController::indexAction
    methods: [POST]
    
app_archive_contact_message:
    path: /archive-contact-message
    controller: App\Controller\ManageContactController::archiveMessageAction
    methods: [POST]

app_view_archived_messages:
    path: /view-archived-messages
    controller: App\Controller\ViewArchivedMessagesController::indexAction
    
app_delete_archived_message:
    path: /delete-archived-message
    controller: App\Controller\DeleteArchivedMesssageController::deleteMessage
    methods: [POST]
