controllers:
    resource: ../src/Controller/
    type: attribute

# app_lucky_number:
#     path: /lucky/number
#     controller: App\Controller\LuckyNumberController::number

app_contact_form:
    path: /contact-form
    controller: App\Controller\ContactFormController::index

app_home:
    path: /
    controller: App\Controller\IndexController::indexAction
    
app_about:
    path: /about
    controller: App\Controller\AboutController::indexAction
