controllers:
    resource: ../src/Controller/
    type: attribute

# app_lucky_number:
#     path: /lucky/number
#     controller: App\Controller\LuckyNumberController::number

app_contact:
    path: /contact
    controller: App\Controller\ContactController::index
    methods: [GET, POST]

app_home:
    path: /
    controller: App\Controller\IndexController::indexAction
    
app_about:
    path: /about
    controller: App\Controller\AboutController::indexAction
    
app_view_contact:
    path: /view-contact-messages
    controller: App\Controller\ViewContactController::indexAction
